Mrf 60086/improve bids debugging script
Marfeel/Prebid.js pull request #41
Opened 2019-11-13 17:31 UTC by joanmirallesmrf

2019-11-13 18:18 UTC, pedrolopezmrf approved these changes

2019-11-14 09:46 UTC, pedrolopezmrf approved these changes

2019-11-14 12:24 UTC, adriafolchmrf requested changes

2019-11-14 12:24 UTC, adriafolchmrf commented on src/targeting.js
> +        .filter(bid => bid.referrer === lastLocation)
bidsReceived has been modified to include the referrer?

2019-11-14 12:24 UTC, adriafolchmrf commented on src/targeting.js
> +  const isBidAlreadyRecieved = (bid, lastLocation) => bidsByReferrer[lastLocation] && !!bidsByReferrer[lastLocation].find(bidCached => bidCached.adId === bid.adId);
This shouldn't be `!!bidsByReferrer[lastLocation] && bidsByReferrer[lastLocation].find(bidCached => bidCached.adId === bid.adId);`

2019-11-14 13:07 UTC, adriafolchmrf approved these changes

2019-11-15 10:59 UTC, merged